# Generated by Django 4.1.5 on 2023-01-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piglify', '0002_alter_grocery_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='contact',
            field=models.CharField(choices=[('umut', 'Umut'), ('jonny', 'Jonny'), ('simon', 'Simon')], max_length=10, null=True),
        ),
    ]
