# Generated by Django 4.1.5 on 2023-01-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piglify', '0004_user_alter_grocery_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='piglify.user'),
        ),
    ]
