# Generated by Django 4.1.5 on 2023-01-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piglify', '0005_alter_grocery_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
