# Generated by Django 4.1.5 on 2023-01-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piglify', '0007_alter_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kitchen', 'Kitchen'), ('bath', 'WC + Bath'), ('vacuum', 'Wipe and Vacuum')], max_length=30)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='grocery',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_chore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piglify.chore'),
        ),
    ]
