# Generated by Django 4.1.5 on 2023-01-26 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piglify', '0008_chore_alter_grocery_location_user_initial_chore'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
