# Generated by Django 4.1.5 on 2023-01-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piglify', '0009_chore_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
