# Generated by Django 4.1.5 on 2023-01-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piglify', '0010_alter_chore_date_added_alter_grocery_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
