# Generated by Django 4.1.5 on 2023-01-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piglify', '0011_user_done_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='done_date',
            new_name='done',
        ),
    ]
