# Generated by Django 4.1.5 on 2023-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piglify', '0013_user_done_date_alter_user_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='desc',
            field=models.CharField(max_length=2000),
        ),
    ]
