# Generated by Django 4.1.5 on 2024-05-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piglify', '0014_alter_chore_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='name',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bath', 'Bath + Restroom'), ('vacuum', 'Wipe and Vacuum')], max_length=30),
        ),
    ]
