version: '3.3'

services:
  backend:
    image: django-backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
  
  frontend:
    image: piglify-frontend:latest
    command: nginx -g "daemon off;"
    ports:
      - 80:80