version: '3'

services:
  frontend:
    restart: always
    image: piglify-frontend:latest
    env_file: .env
    ports:
      - 80:80

  backend:
    restart: always
    image: piglify-backend:latest
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ./backend/db.sqlite3:/usr/app/db.sqlite3
      - ./backend/media/profiles/:/usr/app/media/profiles/
