version: '3.3'

services:
  backend:
    image: django-backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev